# Configuration file for Prettier

printWidth: 120
tabWidth: 2
useTabs: false
semi: false
trailingComma: 'none'
bracketSpacing: false
arrowParens: 'always'
proseWrap: 'preserve'
endOfLine: 'lf'
singleAttributePerLine: false

overrides:
- files: '*.css'
  options:
    printWidth: 120
    singleQuote: false
- files: '*.js'
  options:
    singleQuote: true
