# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Hooks and config updated 2023-11-01

minimum_pre_commit_version: '2.10.0'

default_language_version:
  python: python3

default_stages: [commit]

exclude: '\.min\.(css|js)(\.map)?$|jquery\.stellar\.js$|icomoon\.css$|magnific-popup\.css$|^example-site/themes/lektor-icon$'


repos:
# Meta checks
- repo: meta
  hooks:
  - id: check-useless-excludes

# General fixers
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    name: Trim trailing whitespace
    exclude_types: [svg]
  - id: mixed-line-ending
    name: Normalize mixed line endings
    args: [--fix=lf]
    exclude_types: [batch]
  - id: end-of-file-fixer
    name: Fix end of files
    exclude_types: [svg]
  - id: fix-byte-order-marker
    name: Remove Unicode BOM

# More general fixers
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.1
  hooks:
  - id: remove-tabs
    name: Replace tabs with spaces
    types: [text]
    exclude_types: [svg, batch]
    args: [--whitespaces-count, '2']

# Check and fix spelling
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  # Define separate hooks for checking and correcting spelling errors
  # since codespell doesn't print verbose output when writing changes
  - id: codespell
    name: Check spelling
    exclude: '\.gitattributes'
  - id: codespell
    name: Fix spelling
    exclude: '\.gitattributes'
    args: [--write-changes]

# Format CSS with Prettier
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.3
  hooks:
  - id: prettier
    name: Format CSS (Prettier)
    types: [css]

# Lint and fix CSS with stylelint
- repo: https://github.com/awebdeveloper/pre-commit-stylelint
  rev: '0.0.2'
  hooks:
  - id: stylelint
    name: Lint and fix CSS (stylelint)
    args: [--fix, --color, --maxWarnings, '0']
    additional_dependencies:
    - 'stylelint@15.11.0'
    - 'stylelint-config-standard@34.0.0'
    - 'stylelint-csstree-validator@3.0.0'
    - 'stylelint-declaration-block-no-ignored-properties@2.7.0'
    - 'stylelint-no-unsupported-browser-features@7.0.0'
    - 'stylelint-order@6.0.3'

# Pretty-format INI
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-ini
    name: Format INI
    types: [ini]
    args: [--autofix]

# Format JavaScript with Prettier
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.3
  hooks:
  - id: prettier
    name: Format JavaScript (Prettier)
    types: [javascript]

# Lint and fix JavaScript
- repo: https://github.com/eslint/eslint
  rev: v8.52.0
  hooks:
  - id: eslint
    name: Lint and fix JavaScript (ESLint)
    args: [--fix, --max-warnings, '0', --color --report-unused-disable-directives]
    additional_dependencies:
    - 'eslint-config-standard@17.1.0'
    - 'eslint-config-prettier@v9.0.0'
    - 'eslint-plugin-import@2.29.0'
    - 'eslint-plugin-n@16.2.0'
    - 'eslint-plugin-promise@6.1.1'

# Lint Jinja
- repo: https://github.com/thibaudcolas/curlylint
  rev: v0.13.1
  hooks:
  - id: curlylint
    name: Lint Jinja templates
    types: [html]
    files: 'templates/'

# Check JSON
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
    name: Check JSON

# Add doctoc to Markdown
- repo: https://github.com/thlorenz/doctoc
  rev: v2.2.0
  hooks:
  - id: doctoc
    name: Generate Markdown ToCs
    args: [--maxlevel, '3', --update-only]

# Lint Markdown
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.37.0
  hooks:
  - id: markdownlint
    name: Lint Markdown
    args: [--fix]

# Check Python dependencies
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.2
  hooks:
  - id: python-safety-dependencies-check
    name: Check Python dependencies (Safety)
    files: '.*requirements.*.txt'
    types: [text]

# Check TOML and XML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-toml
    name: Check TOML
  - id: check-xml
    name: Check XML

# Pretty-format YAML
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    name: Format YAML
    args: [--autofix, --indent, '2', --preserve-quotes]

# Check YAML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
    name: Check YAML

# Lint YAML
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.32.0
  hooks:
  - id: yamllint
    name: Lint YAML
    types: [yaml]
    args: [-s, -f, colored]

# Replace CRLF with LF post-prettify
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.1
  hooks:
  - id: remove-crlf
    name: Replace CRLFs with LF
    types: [text]
    exclude_types: [batch, svg]


# General checkers

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: text-unicode-replacement-char
    name: Check for Unicode replacement chars

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
    name: Check for added large files
    args: [--maxkb=1025]
  - id: check-case-conflict
    name: Check for case conflicts
  - id: check-executables-have-shebangs
    name: Check that executables have shebangs
    exclude: 'pre\-commit\-config\.yaml'
  - id: check-shebang-scripts-are-executable
    name: Check that shebangs are executable
    exclude: 'pre\-commit\-config\.yaml'
  - id: check-merge-conflict
    name: Check for merge conflicts


# Commit message hooks #

# Check that commit message follows basic rules
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
    name: Check commit message

# Check commit message spelling
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    name: Check commit message spelling
    stages: [commit-msg]
